version: "3.8"
services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow_dockerfile
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./volume:/home/mlflow/

  scripts:
    depends_on:
      - mlflow
    build:
      context: .
      dockerfile: script_dockerfile
    volumes:
        - ./volume:/home/scripts/
    restart: on-failure